version: "2"
services:
    mysql:
        image: mariadb:10.3.1
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ./data/mariadb:/var/lib/mysql
        env_file:
            - ./app/env/.env

    nginx:
        build: ./nginx/
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - app

    php:
        build: ./php/
        expose:
            - 9000
        links:
            - mysql
        volumes_from:
            - app
        env_file:
            - ./app/env/.env
            
    app:
        image: alpine:3.6
        volumes:
            - ./app:/var/www/html
        command: "true"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql