version: "2"
services:
    mysql:
        image: mariadb:10.3.1
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ./data/mariadb:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=craftcms
            - MYSQL_USER=craftcms
            - MYSQL_PASSWORD=test

    nginx:
        build: ./nginx/
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - app

    php:
        build: ./php/
        expose:
            - 9000
        links:
            - mysql
        volumes_from:
            - app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql

    app:
        image: alpine:3.6
        volumes:
            - ./app:/srv/www/craft
        command: "true"
